/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlatformAdminRouteImport } from './routes/platform-admin'
import { Route as MerchantAdminRouteImport } from './routes/merchant-admin'
import { Route as ShopSlugRouteImport } from './routes/$shopSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerLoginRouteImport } from './routes/seller/login'
import { Route as ShopSlugAdminRouteImport } from './routes/$shopSlug.admin'
import { Route as ShopSlugProductSlugRouteImport } from './routes/$shopSlug.$productSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/platform-admin.lazy').then((d) => d.Route),
)
const MerchantAdminRoute = MerchantAdminRouteImport.update({
  id: '/merchant-admin',
  path: '/merchant-admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/merchant-admin.lazy').then((d) => d.Route),
)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$shopSlug',
  path: '/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerLoginRoute = SellerLoginRouteImport.update({
  id: '/seller/login',
  path: '/seller/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/seller/login.lazy').then((d) => d.Route))
const ShopSlugAdminRoute = ShopSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShopSlugRoute,
} as any)
const ShopSlugProductSlugRoute = ShopSlugProductSlugRouteImport.update({
  id: '/$productSlug',
  path: '/$productSlug',
  getParentRoute: () => ShopSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shopSlug': typeof ShopSlugRouteWithChildren
  '/merchant-admin': typeof MerchantAdminRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$shopSlug/$productSlug': typeof ShopSlugProductSlugRoute
  '/$shopSlug/admin': typeof ShopSlugAdminRoute
  '/seller/login': typeof SellerLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shopSlug': typeof ShopSlugRouteWithChildren
  '/merchant-admin': typeof MerchantAdminRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$shopSlug/$productSlug': typeof ShopSlugProductSlugRoute
  '/$shopSlug/admin': typeof ShopSlugAdminRoute
  '/seller/login': typeof SellerLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shopSlug': typeof ShopSlugRouteWithChildren
  '/merchant-admin': typeof MerchantAdminRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$shopSlug/$productSlug': typeof ShopSlugProductSlugRoute
  '/$shopSlug/admin': typeof ShopSlugAdminRoute
  '/seller/login': typeof SellerLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$shopSlug'
    | '/merchant-admin'
    | '/platform-admin'
    | '/sitemap.xml'
    | '/$shopSlug/$productSlug'
    | '/$shopSlug/admin'
    | '/seller/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$shopSlug'
    | '/merchant-admin'
    | '/platform-admin'
    | '/sitemap.xml'
    | '/$shopSlug/$productSlug'
    | '/$shopSlug/admin'
    | '/seller/login'
  id:
    | '__root__'
    | '/'
    | '/$shopSlug'
    | '/merchant-admin'
    | '/platform-admin'
    | '/sitemap.xml'
    | '/$shopSlug/$productSlug'
    | '/$shopSlug/admin'
    | '/seller/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopSlugRoute: typeof ShopSlugRouteWithChildren
  MerchantAdminRoute: typeof MerchantAdminRoute
  PlatformAdminRoute: typeof PlatformAdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SellerLoginRoute: typeof SellerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-admin': {
      id: '/merchant-admin'
      path: '/merchant-admin'
      fullPath: '/merchant-admin'
      preLoaderRoute: typeof MerchantAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shopSlug': {
      id: '/$shopSlug'
      path: '/$shopSlug'
      fullPath: '/$shopSlug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/login': {
      id: '/seller/login'
      path: '/seller/login'
      fullPath: '/seller/login'
      preLoaderRoute: typeof SellerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shopSlug/admin': {
      id: '/$shopSlug/admin'
      path: '/admin'
      fullPath: '/$shopSlug/admin'
      preLoaderRoute: typeof ShopSlugAdminRouteImport
      parentRoute: typeof ShopSlugRoute
    }
    '/$shopSlug/$productSlug': {
      id: '/$shopSlug/$productSlug'
      path: '/$productSlug'
      fullPath: '/$shopSlug/$productSlug'
      preLoaderRoute: typeof ShopSlugProductSlugRouteImport
      parentRoute: typeof ShopSlugRoute
    }
  }
}

interface ShopSlugRouteChildren {
  ShopSlugProductSlugRoute: typeof ShopSlugProductSlugRoute
  ShopSlugAdminRoute: typeof ShopSlugAdminRoute
}

const ShopSlugRouteChildren: ShopSlugRouteChildren = {
  ShopSlugProductSlugRoute: ShopSlugProductSlugRoute,
  ShopSlugAdminRoute: ShopSlugAdminRoute,
}

const ShopSlugRouteWithChildren = ShopSlugRoute._addFileChildren(
  ShopSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopSlugRoute: ShopSlugRouteWithChildren,
  MerchantAdminRoute: MerchantAdminRoute,
  PlatformAdminRoute: PlatformAdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SellerLoginRoute: SellerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
